package icbm.explosion.model.tiles;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelRadarStation extends ModelBase
{
    // fields
    ModelRenderer Base;
    ModelRenderer Battery;
    ModelRenderer BatRing1;
    ModelRenderer BatRing2;
    ModelRenderer BatRing3;
    ModelRenderer BatRing4;
    ModelRenderer LeftPlate;
    ModelRenderer RightPlate;
    ModelRenderer Panel;
    ModelRenderer SignalPole;
    ModelRenderer SignalRec;
    ModelRenderer SignalRing1;
    ModelRenderer SignalRing2;
    ModelRenderer Strut1;
    ModelRenderer Strut2;
    ModelRenderer LeftPlateEnd;
    ModelRenderer RightPlateEnd;
    ModelRenderer BaseBump1;
    ModelRenderer BaseBump2;
    ModelRenderer FrontWireTop;
    ModelRenderer BackWireTop;
    ModelRenderer FrontWireBottom;
    ModelRenderer BackWireBottom;
    ModelRenderer BatteryPole;
    ModelRenderer PistonHead;
    ModelRenderer PistonPole;
    ModelRenderer PistonBody;

    public ModelRadarStation()
    {
        textureWidth = 128;
        textureHeight = 128;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(0F, 0F, 0F, 11, 4, 14);
        Base.setRotationPoint(-7F, 20F, -7F);
        Base.setTextureSize(128, 128);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Battery = new ModelRenderer(this, 51, 0);
        Battery.addBox(0F, 0F, 0F, 3, 3, 7);
        Battery.setRotationPoint(4F, 21F, -0.5F);
        Battery.setTextureSize(128, 128);
        Battery.mirror = true;
        setRotation(Battery, 0F, 0F, 0F);
        BatRing1 = new ModelRenderer(this, 51, 11);
        BatRing1.addBox(0F, 0F, 0F, 3, 3, 1);
        BatRing1.setRotationPoint(4F, 21F, -2F);
        BatRing1.setTextureSize(128, 128);
        BatRing1.mirror = true;
        setRotation(BatRing1, 0F, 0F, 0F);
        BatRing2 = new ModelRenderer(this, 51, 16);
        BatRing2.addBox(0F, 0F, 0F, 3, 3, 1);
        BatRing2.setRotationPoint(4F, 21F, -3.5F);
        BatRing2.setTextureSize(128, 128);
        BatRing2.mirror = true;
        setRotation(BatRing2, 0F, 0F, 0F);
        BatRing3 = new ModelRenderer(this, 51, 21);
        BatRing3.addBox(0F, 0F, 0F, 3, 3, 1);
        BatRing3.setRotationPoint(4F, 21F, -5F);
        BatRing3.setTextureSize(128, 128);
        BatRing3.mirror = true;
        setRotation(BatRing3, 0F, 0F, 0F);
        BatRing4 = new ModelRenderer(this, 51, 26);
        BatRing4.addBox(0F, 0F, 0F, 3, 3, 1);
        BatRing4.setRotationPoint(4F, 21F, -6.5F);
        BatRing4.setTextureSize(128, 128);
        BatRing4.mirror = true;
        setRotation(BatRing4, 0F, 0F, 0F);
        LeftPlate = new ModelRenderer(this, 0, 19);
        LeftPlate.addBox(0F, 0F, 0F, 1, 3, 9);
        LeftPlate.setRotationPoint(-7F, 17F, -2F);
        LeftPlate.setTextureSize(128, 128);
        LeftPlate.mirror = true;
        setRotation(LeftPlate, 0F, 0F, 0F);
        RightPlate = new ModelRenderer(this, 21, 19);
        RightPlate.addBox(0F, 0F, 0F, 1, 3, 9);
        RightPlate.setRotationPoint(3F, 17F, -2F);
        RightPlate.setTextureSize(128, 128);
        RightPlate.mirror = true;
        setRotation(RightPlate, 0F, 0F, 0F);
        Panel = new ModelRenderer(this, 0, 32);
        Panel.addBox(0F, 0F, 0F, 8, 7, 1);
        Panel.setRotationPoint(-5.5F, 11F, 5F);
        Panel.setTextureSize(128, 128);
        Panel.mirror = true;
        setRotation(Panel, -0.6108652F, 0F, 0F);
        SignalPole = new ModelRenderer(this, 60, 11);
        SignalPole.addBox(-0.5F, 0F, -0.5F, 1, 14, 1);
        SignalPole.setRotationPoint(4.5F, 10F, 6.5F);
        SignalPole.setTextureSize(128, 128);
        SignalPole.mirror = true;
        setRotation(SignalPole, 0F, 0F, 0F);
        SignalRec = new ModelRenderer(this, 60, 27);
        SignalRec.addBox(-1F, -1F, -1F, 2, 2, 2);
        SignalRec.setRotationPoint(4.5F, 10F, 6.5F);
        SignalRec.setTextureSize(128, 128);
        SignalRec.mirror = true;
        setRotation(SignalRec, 0F, 0F, 0F);
        SignalRing1 = new ModelRenderer(this, 65, 11);
        SignalRing1.addBox(-1F, 0F, -1F, 2, 1, 2);
        SignalRing1.setRotationPoint(4.5F, 11.5F, 6.5F);
        SignalRing1.setTextureSize(128, 128);
        SignalRing1.mirror = true;
        setRotation(SignalRing1, 0F, 0F, 0F);
        SignalRing2 = new ModelRenderer(this, 65, 15);
        SignalRing2.addBox(-1F, -0.5F, -1F, 2, 1, 2);
        SignalRing2.setRotationPoint(4.5F, 13.5F, 6.5F);
        SignalRing2.setTextureSize(128, 128);
        SignalRing2.mirror = true;
        setRotation(SignalRing2, 0F, 0F, 0F);
        Strut1 = new ModelRenderer(this, 42, 19);
        Strut1.addBox(0F, 0F, 0F, 2, 3, 2);
        Strut1.setRotationPoint(-2.5F, 16F, 2F);
        Strut1.setTextureSize(128, 128);
        Strut1.mirror = true;
        setRotation(Strut1, 0.8412487F, 0F, 0F);
        Strut2 = new ModelRenderer(this, 19, 32);
        Strut2.addBox(0F, 0F, 0F, 3, 4, 2);
        Strut2.setRotationPoint(-3F, 16.5F, 4F);
        Strut2.setTextureSize(128, 128);
        Strut2.mirror = true;
        setRotation(Strut2, 0F, 0F, 0F);
        LeftPlateEnd = new ModelRenderer(this, 42, 25);
        LeftPlateEnd.addBox(0F, 0F, 0F, 1, 2, 1);
        LeftPlateEnd.setRotationPoint(-7F, 18F, -3F);
        LeftPlateEnd.setTextureSize(128, 128);
        LeftPlateEnd.mirror = true;
        setRotation(LeftPlateEnd, 0F, 0F, 0F);
        RightPlateEnd = new ModelRenderer(this, 42, 29);
        RightPlateEnd.addBox(0F, 0F, 0F, 1, 2, 1);
        RightPlateEnd.setRotationPoint(3F, 18F, -3F);
        RightPlateEnd.setTextureSize(128, 128);
        RightPlateEnd.mirror = true;
        setRotation(RightPlateEnd, 0F, 0F, 0F);
        BaseBump1 = new ModelRenderer(this, 0, 41);
        BaseBump1.addBox(0F, 0F, 0F, 9, 1, 1);
        BaseBump1.setRotationPoint(-6F, 19F, -2F);
        BaseBump1.setTextureSize(128, 128);
        BaseBump1.mirror = true;
        setRotation(BaseBump1, 0F, 0F, 0F);
        BaseBump2 = new ModelRenderer(this, 0, 44);
        BaseBump2.addBox(0F, 0F, 0F, 10, 1, 1);
        BaseBump2.setRotationPoint(-6.5F, 19.5F, -3.5F);
        BaseBump2.setTextureSize(128, 128);
        BaseBump2.mirror = true;
        setRotation(BaseBump2, 0F, 0F, 0F);
        FrontWireTop = new ModelRenderer(this, 30, 32);
        FrontWireTop.addBox(0F, 0F, 0F, 2, 1, 1);
        FrontWireTop.setRotationPoint(4F, 19F, 1F);
        FrontWireTop.setTextureSize(128, 128);
        FrontWireTop.mirror = true;
        setRotation(FrontWireTop, 0F, 0F, 0F);
        BackWireTop = new ModelRenderer(this, 30, 35);
        BackWireTop.addBox(0F, 0F, 0F, 2, 1, 1);
        BackWireTop.setRotationPoint(4F, 19F, 4F);
        BackWireTop.setTextureSize(128, 128);
        BackWireTop.mirror = true;
        setRotation(BackWireTop, 0F, 0F, 0F);
        FrontWireBottom = new ModelRenderer(this, 42, 33);
        FrontWireBottom.addBox(0F, 0F, 0F, 1, 1, 1);
        FrontWireBottom.setRotationPoint(5F, 20F, 1F);
        FrontWireBottom.setTextureSize(128, 128);
        FrontWireBottom.mirror = true;
        setRotation(FrontWireBottom, 0F, 0F, 0F);
        BackWireBottom = new ModelRenderer(this, 42, 36);
        BackWireBottom.addBox(0F, 0F, 0F, 1, 1, 1);
        BackWireBottom.setRotationPoint(5F, 20F, 4F);
        BackWireBottom.setTextureSize(128, 128);
        BackWireBottom.mirror = true;
        setRotation(BackWireBottom, 0F, 0F, 0F);
        BatteryPole = new ModelRenderer(this, 65, 19);
        BatteryPole.addBox(0F, 0F, 0F, 1, 1, 6);
        BatteryPole.setRotationPoint(5F, 22F, -6F);
        BatteryPole.setTextureSize(128, 128);
        BatteryPole.mirror = true;
        setRotation(BatteryPole, 0F, 0F, 0F);
        PistonHead = new ModelRenderer(this, 51, 31);
        PistonHead.addBox(0F, 0F, 0F, 1, 1, 2);
        PistonHead.setRotationPoint(-2F, 19F, -6.2F);
        PistonHead.setTextureSize(128, 128);
        PistonHead.mirror = true;
        setRotation(PistonHead, 0F, 0F, 0F);
        PistonPole = new ModelRenderer(this, 51, 35);
        PistonPole.addBox(0F, 0F, 0F, 3, 1, 1);
        PistonPole.setRotationPoint(-1F, 19.25F, -5.7F);
        PistonPole.setTextureSize(128, 128);
        PistonPole.mirror = true;
        setRotation(PistonPole, 0F, 0F, 0F);
        PistonBody = new ModelRenderer(this, 51, 38);
        PistonBody.addBox(0F, 0F, 0F, 3, 1, 2);
        PistonBody.setRotationPoint(0F, 19F, -6.2F);
        PistonBody.setTextureSize(128, 128);
        PistonBody.mirror = true;
        setRotation(PistonBody, 0F, 0F, 0F);
    }

    public void render(float f5, float rotationScreen, float rotationRod)
    {
        Base.render(f5);
        Battery.render(f5);
        BatRing1.render(f5);
        BatRing2.render(f5);
        BatRing3.render(f5);
        BatRing4.render(f5);
        LeftPlate.render(f5);
        RightPlate.render(f5);

        Panel.rotateAngleX = -0.6108652F + rotationScreen;
        Panel.render(f5);

        SignalPole.rotateAngleY = rotationRod;
        SignalPole.render(f5);
        SignalRec.rotateAngleY = rotationRod;
        SignalRec.render(f5);
        SignalRing1.rotateAngleY = rotationRod;
        SignalRing1.render(f5);
        SignalRing2.rotateAngleY = rotationRod;
        SignalRing2.render(f5);

        Strut1.render(f5);
        Strut2.render(f5);
        LeftPlateEnd.render(f5);
        RightPlateEnd.render(f5);
        BaseBump1.render(f5);
        BaseBump2.render(f5);
        FrontWireTop.render(f5);
        BackWireTop.render(f5);
        FrontWireBottom.render(f5);
        BackWireBottom.render(f5);
        BatteryPole.render(f5);
        PistonHead.render(f5);
        PistonPole.render(f5);
        PistonBody.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
