// Date: 3/6/12 12:22:51 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape17;
    ModelRenderer Shape20;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape7 = new ModelRenderer(this, 35, 52);
      Shape7.addBox(0F, 0F, 0F, 1, 41, 4);
      Shape7.setRotationPoint(-6F, -24F, -2F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 20);
      Shape8.addBox(0F, 0F, 0F, 2, 12, 2);
      Shape8.setRotationPoint(-8F, 11F, -1F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 46, 52);
      Shape9.addBox(0F, 0F, 0F, 3, 19, 2);
      Shape9.setRotationPoint(-5F, -2F, -1F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 10);
      Shape10.addBox(0F, 0F, 0F, 2, 4, 2);
      Shape10.setRotationPoint(-7F, -28F, -1F);
      Shape10.setTextureSize(128, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 57, 52);
      Shape17.addBox(0F, 0F, 0F, 9, 6, 6);
      Shape17.setRotationPoint(-6F, 17F, -3F);
      Shape17.setTextureSize(128, 128);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 32, 0);
      Shape20.addBox(0F, 0F, 0F, 16, 1, 8);
      Shape20.setRotationPoint(-8F, 23F, -4F);
      Shape20.setTextureSize(128, 128);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape17.render(f5);
    Shape20.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
